FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /FastAPI

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .
COPY scripts.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
